import type { TemplateHelpers } from './template-helpers';
import type { UpdateDtoParams } from './types';
import { name as packageName, version as packageVersion } from '../../package.json';

interface GenerateUpdateDtoParam extends UpdateDtoParams {
  exportRelationModifierClasses: boolean;
  templateHelpers: TemplateHelpers;
}
export const generateUpdateDto = ({
  model,
  fields,
  imports,
  extraClasses,
  apiExtraModels,
  exportRelationModifierClasses,
  templateHelpers: t,
}: GenerateUpdateDtoParam) => `
// @@generated by ${packageName}@${packageVersion}. ${new Date().toLocaleString('sv-SE')}.
// modification to this file may be overwritten when regenerating.
${t.importStatements(imports)}

${t.each(
  extraClasses,
  exportRelationModifierClasses ? (content) => `export ${content}` : t.echo,
  '\n',
)}

${t.if(apiExtraModels.length, t.apiExtraModels(apiExtraModels))}
export ${t.config.outputType} ${t.updateDtoName(model.name)} {
  ${t.fieldsToDtoProps(fields, 'update', true)}
}
`;
