import type { TemplateHelpers } from './template-helpers';
import type { CreateDtoParams } from './types';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { name, version } = require('../../package.json');

interface GenerateCreateDtoParam extends CreateDtoParams {
  exportRelationModifierClasses: boolean;
  templateHelpers: TemplateHelpers;
}
export const generateCreateDto = ({
  model,
  fields,
  imports,
  extraClasses,
  apiExtraModels,
  exportRelationModifierClasses,
  templateHelpers: t,
}: GenerateCreateDtoParam) => `
// @@generated by ${name}@${version}. ${new Date().toLocaleString('sv-SE')}
// modification to this file may be overwritten when regenerating.
${t.importStatements(imports)}

${t.each(
  extraClasses,
  exportRelationModifierClasses ? (content) => `export ${content}` : t.echo,
  '\n',
)}

${t.if(apiExtraModels.length, t.apiExtraModels(apiExtraModels))}
export ${t.config.outputType} ${t.createDtoName(model.name)} {
  ${t.fieldsToDtoProps(fields, 'create', true)}
}
`;
